export const baseInputClass = [
  'h-10 w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2 text-sm text-gray-900 shadow-sm',
  'placeholder:text-gray-400',
  'transition-all duration-200 ease-in-out',
  'hover:border-gray-400',
  'focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20',
  'disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 disabled:border-gray-200',
].join(' ');

export const inputLabelClass = 'text-sm font-medium text-gray-600';

export const antdInputNumberClass = [
  'w-full',
  '[&.ant-input-number]:h-10',
  '[&.ant-input-number]:rounded-lg',
  '[&.ant-input-number]:border-gray-300',
  '[&.ant-input-number]:bg-white',
  '[&.ant-input-number]:shadow-sm',
  '[&.ant-input-number]:transition-all',
  '[&.ant-input-number:hover]:border-gray-400',
  '[&.ant-input-number-focused]:border-blue-500',
  '[&.ant-input-number-focused]:shadow-[0_0_0_2px_rgba(59,130,246,0.2)]',
  '[&.ant-input-number-disabled]:bg-gray-50',
  '[&.ant-input-number-disabled]:border-gray-200',
  '[&.border-red-500.ant-input-number]:border-red-500',
  '[&_.ant-input-number-input]:h-10',
  '[&_.ant-input-number-input]:px-3.5',
  '[&_.ant-input-number-input]:py-2',
  '[&_.ant-input-number-input]:text-sm',
  '[&_.ant-input-number-input]:text-gray-900',
  '[&_.ant-input-number-input]:placeholder:text-gray-400',
  '[&.ant-input-number-disabled_.ant-input-number-input]:text-gray-500',
].join(' ');

export const antdSelectClass = [
  'w-full',
  '[&_.ant-select-selector]:min-h-10',
  '[&_.ant-select-selector]:rounded-lg',
  '[&_.ant-select-selector]:border-gray-300',
  '[&_.ant-select-selector]:bg-white',
  '[&_.ant-select-selector]:shadow-sm',
  '[&_.ant-select-selector]:px-3.5',
  '[&_.ant-select-selector]:py-1.5',
  '[&_.ant-select-selector]:transition-all',
  '[&_.ant-select-selection-item]:text-sm',
  '[&_.ant-select-selection-item]:text-gray-900',
  '[&_.ant-select-selection-placeholder]:text-sm',
  '[&_.ant-select-selection-placeholder]:text-gray-400',
  '[&_.ant-select-selection-search-input]:text-sm',
  '[&.ant-select:hover_.ant-select-selector]:border-gray-400',
  '[&.ant-select-focused_.ant-select-selector]:border-blue-500',
  '[&.ant-select-focused_.ant-select-selector]:shadow-[0_0_0_2px_rgba(59,130,246,0.2)]',
  '[&.ant-select-disabled_.ant-select-selector]:bg-gray-50',
  '[&.ant-select-disabled_.ant-select-selector]:border-gray-200',
  '[&.ant-select-disabled_.ant-select-selection-item]:text-gray-500',
  '[&.ant-select-disabled_.ant-select-selection-placeholder]:text-gray-400',
  '[&.border-red-500_.ant-select-selector]:border-red-500',
].join(' ');

export const antdDatePickerClass = [
  'w-full',
  '[&.ant-picker]:h-10',
  '[&.ant-picker]:rounded-lg',
  '[&.ant-picker]:border-gray-300',
  '[&.ant-picker]:bg-white',
  '[&.ant-picker]:px-3.5',
  '[&.ant-picker]:py-2',
  '[&.ant-picker]:shadow-sm',
  '[&.ant-picker]:transition-all',
  '[&.ant-picker:hover]:border-gray-400',
  '[&.ant-picker-focused]:border-blue-500',
  '[&.ant-picker-focused]:shadow-[0_0_0_2px_rgba(59,130,246,0.2)]',
  '[&.ant-picker-disabled]:bg-gray-50',
  '[&.ant-picker-disabled]:border-gray-200',
  '[&.border-red-500.ant-picker]:border-red-500',
  '[&_.ant-picker-input>input]:text-sm',
  '[&_.ant-picker-input>input]:text-gray-900',
  '[&_.ant-picker-input>input]:placeholder:text-gray-400',
  '[&.ant-picker-disabled_.ant-picker-input>input]:text-gray-500',
].join(' ');
